feat(package.json): Update package name
namecheap/express-inversify pull request #1
Opened 2021-10-04 16:32 UTC by yehor-manzhula

## Description
Update package name, readme file

## Motivation and Context
After fork package name needs to be update

## How Has This Been Tested?
Tests are green, build is green

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-10-06 08:14 UTC, b1ff reviewed
please fix references to packages - add @namecheap scope

2021-10-06 08:14 UTC, b1ff commented on README.md
> +You can install `express-inversify` using npm:
```suggestion
You can install `@namecheap/express-inversify` using npm:
```

2021-10-06 08:14 UTC, b1ff commented on README.md
> +npm install inversify express-inversify reflect-metadata --save
```suggestion
npm install inversify @namecheap/express-inversify reflect-metadata --save
```

2021-10-06 08:14 UTC, b1ff commented on README.md
> +import { interfaces, controller, httpGet, httpPost, httpDelete, request, queryParam, response, requestParam } from "express-inversify";
```suggestion
import { interfaces, controller, httpGet, httpPost, httpDelete, request, queryParam, response, requestParam } from "@namecheap/express-inversify";
```

2021-10-06 08:14 UTC, b1ff commented on README.md
> +import { interfaces, InversifyExpressServer, TYPE } from 'express-inversify';
```suggestion
import { interfaces, InversifyExpressServer, TYPE } from '@namecheap/express-inversify';
```

2021-10-06 08:14 UTC, b1ff commented on README.md
> +import { cleanUpMetadata } from "express-inversify";
```suggestion
import { cleanUpMetadata } from "@namecheap/express-inversify";
```

2021-10-06 08:14 UTC, b1ff commented on README.md
> +} from "express-inversify";
```suggestion
} from "@namecheap/express-inversify";
```

2021-10-06 08:14 UTC, b1ff commented on README.md
> +} from "express-inversify";
```suggestion
} from "@namecheap/express-inversify";
```

2021-10-06 11:42 UTC, StyleT commented
Here we should switch license to `Apache-2.0` and add `NOTICE.md` file, see examples:
- https://github.com/namecheap/ilc/blob/master/NOTICE.md
- https://github.com/namecheap/ilc/blob/master/LICENSE.txt

2021-10-06 12:51 UTC, b1ff approved these changes

2021-10-06 21:41 UTC, StyleT requested changes

2021-10-06 21:41 UTC, StyleT commented on package.json
>    "license": "MIT",
Pls correct version here too

2021-10-06 21:41 UTC, StyleT commented on package.json
>    "author": "Cody Simms",
Namecheap, Inc

2021-10-07 09:06 UTC, StyleT approved these changes

2021-10-20 12:04 UTC, merged